-- apex-create.sql.tpl — Creates Sample Notes & Vector Search APEX app (ID 100)
-- Run as __APEX_USER__: sqlplus __APEX_USER__/__APEX_PASSWORD__@__SERVICE_NAME__ @apex-create.sql
-- Uses the APEX import API (wwv_flow_imp / wwv_imp_workspace / wwv_flow_imp_shared)
-- — the same packages used by APEX Builder export files.
-- Generated from apex-create.sql.tpl — do not edit this file directly

SET SERVEROUTPUT ON SIZE UNLIMITED
SET DEFINE OFF
WHENEVER SQLERROR CONTINUE

-- ── 0. Workspace + application install context ────────────────────────────────
DECLARE
  l_ws_id NUMBER;
BEGIN
  SELECT workspace_id INTO l_ws_id
  FROM   apex_workspaces
  WHERE  workspace = '__APEX_USER__';
  DBMS_OUTPUT.PUT_LINE('[0] Workspace ID: ' || l_ws_id);

  wwv_flow_api.set_security_group_id(p_security_group_id => l_ws_id);
  apex_240200.wwv_flow_application_install.set_workspace_id(l_ws_id);
  apex_240200.wwv_flow_application_install.set_application_id(100);
  DBMS_OUTPUT.PUT_LINE('[0] Context OK');
EXCEPTION WHEN NO_DATA_FOUND THEN
  RAISE_APPLICATION_ERROR(-20001,
    'Workspace "__APEX_USER__" not found. Run run-adb-26ai.sh first.');
END;
/

-- ── 0b. Start APEX import component context ───────────────────────────────────
DECLARE
  l_ws_id NUMBER;
BEGIN
  SELECT workspace_id INTO l_ws_id
  FROM   apex_workspaces
  WHERE  workspace = '__APEX_USER__';

  apex_240200.wwv_flow_imp.component_begin(
    p_version_yyyy_mm_dd   => '2024.05.31',
    p_default_workspace_id => l_ws_id
  );
  DBMS_OUTPUT.PUT_LINE('[0b] component_begin OK');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('[0b] component_begin FAILED (non-fatal): ' || SQLERRM);
END;
/

-- ── 1. Remove existing app if present ────────────────────────────────────────
BEGIN
  wwv_flow_api.remove_flow(100);
  DBMS_OUTPUT.PUT_LINE('[1] Removed existing App 100');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('[1] No existing App 100 (OK)');
END;
/

-- ── 2. Create application shell ───────────────────────────────────────────────
BEGIN
  apex_240200.wwv_imp_workspace.create_flow(
    p_id            => 100,
    p_owner         => '__APEX_USER__',
    p_name          => 'Notes ' || chr(38) || ' Vector Search',
    p_alias         => 'SAMPLE-NOTES',
    p_flow_language => 'en',
    p_flow_status   => 'AVAILABLE_W_EDIT_LINK'
  );
  DBMS_OUTPUT.PUT_LINE('[2] Application shell created');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('[2] create_flow FAILED: ' || SQLERRM);
  RAISE;
END;
/

-- ── 2b. Create authentication scheme (APEX Accounts) ────────────────────────
--  Flow must exist before this call. The link back from wwv_flows.authentication_id
--  is set by a SYSDBA UPDATE in load-sample-app.sh after this script completes.
BEGIN
  apex_240200.wwv_flow_imp_shared.create_authentication(
    p_id                   => ROUND(DBMS_RANDOM.VALUE(1e9, 9e9)),
    p_flow_id              => 100,
    p_name                 => 'Application Express Authentication',
    p_scheme_type          => 'NATIVE_APEX_ACCOUNTS',
    p_use_secure_cookie_yn => 'N',
    p_ras_mode             => 0
  );
  DBMS_OUTPUT.PUT_LINE('[2b] Authentication scheme (APEX Accounts) created');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('[2b] create_authentication FAILED: ' || SQLERRM);
END;
/

-- ── 3. Wire Universal Theme 42 as the Desktop user interface ──────────────────
BEGIN
  apex_240200.wwv_flow_imp.create_user_interface(
    p_id           => ROUND(DBMS_RANDOM.VALUE(1e9, 9e9)),
    p_flow_id      => 100,
    p_theme_id     => 42,
    p_ui_type_name => 'DESKTOP'
  );
  DBMS_OUTPUT.PUT_LINE('[3] User interface (UT42) created');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('[3] create_user_interface FAILED: ' || SQLERRM);
END;
/

-- ── 3b. Theme subscription is handled by a SYSDBA INSERT in load-sample-app.sh
--  (copies all template IDs from the global UT42 entry — see Step 4 in shell script)

-- ── 4a. Global page (0) ───────────────────────────────────────────────────────
BEGIN
  apex_240200.wwv_flow_wizard_api.create_global_page(
    p_application_id => 100,
    p_page_id        => 0
  );
  DBMS_OUTPUT.PUT_LINE('[4a] Global page (0) OK');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('[4a] create_global_page FAILED: ' || SQLERRM);
END;
/

-- ── 4a2. Navigation Bar list region on global page ────────────────────────────
--  App 102 wires its Navigation Bar list through wwv_flow_themes.default_nav_bar_list_template
--  and navigation_list_id on wwv_flows. The nav bar list (Sign Out etc.) renders via
--  the theme's nav bar list template — no explicit region needed on page 0 for UT42.
--  However we DO need to wire the nav bar list id onto wwv_flows (done in Step 4 of shell).
--  This block is intentionally empty — wiring happens in load-sample-app.sh Step 4g.

-- ── 4b. Login page (9999) ─────────────────────────────────────────────────────
BEGIN
  apex_240200.wwv_flow_wizard_api.create_login_page(
    p_flow_id => 100,
    p_page_id => 9999
  );
  DBMS_OUTPUT.PUT_LINE('[4b] Login page (9999) OK');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('[4b] create_login_page FAILED: ' || SQLERRM);
END;
/

-- ── 4c. Page 1: Notes Interactive Report ─────────────────────────────────────
--  Use p_sql so plug_source is populated (p_table_name leaves it empty → ORA-00903).
--  Worksheet columns are created explicitly below — create_ir_region_on_col_info
--  does NOT populate wwv_flow_worksheet_columns when called via PL/SQL.
DECLARE
  l_region_id   NUMBER := ROUND(DBMS_RANDOM.VALUE(1e9,9e9));
  l_ws_id_p1    NUMBER;
BEGIN
  apex_240200.wwv_flow_wizard_api.create_blank_page(
    p_flow_id   => 100,
    p_page_id   => 1,
    p_name      => 'Notes',
    p_page_mode => 'NORMAL'
  );
  apex_240200.wwv_flow_wizard_api.create_ir_region_on_col_info(
    p_flow_id      => 100,
    p_page_id      => 1,
    p_region_id    => l_region_id,
    p_region_title => 'Notes',
    p_sql          => 'SELECT note_id, title, category, body, created_date FROM __APEX_USER__.notes'
  );

  -- Get the worksheet ID just created
  SELECT id INTO l_ws_id_p1
  FROM   apex_240200.wwv_flow_worksheets
  WHERE  flow_id = 100 AND page_id = 1;

  -- Create worksheet columns explicitly (p_column_type/p_display_as/alignment come
  -- AFTER all p_allow_* params per the wwv_flow_imp.create_worksheet_column signature)
  apex_240200.wwv_flow_imp.create_worksheet_column(
    p_id=>ROUND(DBMS_RANDOM.VALUE(1e9,9e9)), p_flow_id=>100, p_page_id=>1,
    p_worksheet_id=>l_ws_id_p1, p_db_column_name=>'NOTE_ID',
    p_display_order=>1, p_column_identifier=>'A',
    p_column_label=>'Note Id', p_report_label=>'Note Id',
    p_display_in_default_rpt=>'Y', p_is_sortable=>'Y',
    p_allow_sorting=>'Y', p_allow_filtering=>'Y', p_allow_highlighting=>'Y',
    p_allow_ctrl_breaks=>'Y', p_allow_aggregations=>'Y', p_allow_computations=>'Y',
    p_allow_charting=>'Y', p_allow_group_by=>'Y', p_allow_pivot=>'Y', p_allow_hide=>'Y',
    p_column_type=>'NUMBER', p_display_as=>'TEXT',
    p_heading_alignment=>'RIGHT', p_column_alignment=>'RIGHT'
  );
  apex_240200.wwv_flow_imp.create_worksheet_column(
    p_id=>ROUND(DBMS_RANDOM.VALUE(1e9,9e9)), p_flow_id=>100, p_page_id=>1,
    p_worksheet_id=>l_ws_id_p1, p_db_column_name=>'TITLE',
    p_display_order=>2, p_column_identifier=>'B',
    p_column_label=>'Title', p_report_label=>'Title',
    p_display_in_default_rpt=>'Y', p_is_sortable=>'Y',
    p_allow_sorting=>'Y', p_allow_filtering=>'Y', p_allow_highlighting=>'Y',
    p_allow_ctrl_breaks=>'Y', p_allow_aggregations=>'Y', p_allow_computations=>'Y',
    p_allow_charting=>'Y', p_allow_group_by=>'Y', p_allow_pivot=>'Y', p_allow_hide=>'Y',
    p_column_type=>'STRING', p_display_as=>'TEXT',
    p_heading_alignment=>'LEFT', p_column_alignment=>'LEFT'
  );
  apex_240200.wwv_flow_imp.create_worksheet_column(
    p_id=>ROUND(DBMS_RANDOM.VALUE(1e9,9e9)), p_flow_id=>100, p_page_id=>1,
    p_worksheet_id=>l_ws_id_p1, p_db_column_name=>'CATEGORY',
    p_display_order=>3, p_column_identifier=>'C',
    p_column_label=>'Category', p_report_label=>'Category',
    p_display_in_default_rpt=>'Y', p_is_sortable=>'Y',
    p_allow_sorting=>'Y', p_allow_filtering=>'Y', p_allow_highlighting=>'Y',
    p_allow_ctrl_breaks=>'Y', p_allow_aggregations=>'Y', p_allow_computations=>'Y',
    p_allow_charting=>'Y', p_allow_group_by=>'Y', p_allow_pivot=>'Y', p_allow_hide=>'Y',
    p_column_type=>'STRING', p_display_as=>'TEXT',
    p_heading_alignment=>'LEFT', p_column_alignment=>'LEFT'
  );
  apex_240200.wwv_flow_imp.create_worksheet_column(
    p_id=>ROUND(DBMS_RANDOM.VALUE(1e9,9e9)), p_flow_id=>100, p_page_id=>1,
    p_worksheet_id=>l_ws_id_p1, p_db_column_name=>'BODY',
    p_display_order=>4, p_column_identifier=>'D',
    p_column_label=>'Body', p_report_label=>'Body',
    p_display_in_default_rpt=>'Y', p_is_sortable=>'Y',
    p_allow_sorting=>'Y', p_allow_filtering=>'Y', p_allow_highlighting=>'Y',
    p_allow_ctrl_breaks=>'Y', p_allow_aggregations=>'Y', p_allow_computations=>'Y',
    p_allow_charting=>'Y', p_allow_group_by=>'Y', p_allow_pivot=>'Y', p_allow_hide=>'Y',
    p_column_type=>'STRING', p_display_as=>'TEXT',
    p_heading_alignment=>'LEFT', p_column_alignment=>'LEFT'
  );
  apex_240200.wwv_flow_imp.create_worksheet_column(
    p_id=>ROUND(DBMS_RANDOM.VALUE(1e9,9e9)), p_flow_id=>100, p_page_id=>1,
    p_worksheet_id=>l_ws_id_p1, p_db_column_name=>'CREATED_DATE',
    p_display_order=>5, p_column_identifier=>'E',
    p_column_label=>'Created', p_report_label=>'Created',
    p_display_in_default_rpt=>'Y', p_is_sortable=>'Y',
    p_allow_sorting=>'Y', p_allow_filtering=>'Y', p_allow_highlighting=>'Y',
    p_allow_ctrl_breaks=>'Y', p_allow_aggregations=>'Y', p_allow_computations=>'Y',
    p_allow_charting=>'Y', p_allow_group_by=>'Y', p_allow_pivot=>'Y', p_allow_hide=>'Y',
    p_column_type=>'DATE', p_display_as=>'TEXT',
    p_heading_alignment=>'LEFT', p_column_alignment=>'LEFT'
  );

  DBMS_OUTPUT.PUT_LINE('[4c] Page 1 (Notes IR + 5 columns) OK');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('[4c] Page 1 FAILED: ' || SQLERRM);
  RAISE;
END;
/

-- ── 4d+4e. Page 2: Semantic Vector Search IR + P2_SEARCH item + Go button ─────
DECLARE
  l_region_id  NUMBER := ROUND(DBMS_RANDOM.VALUE(1e9,9e9));
  l_label_tpl  NUMBER;
  l_button_tpl NUMBER;
  l_ws_id_p2   NUMBER;
BEGIN
  apex_240200.wwv_flow_wizard_api.create_blank_page(
    p_flow_id   => 100,
    p_page_id   => 2,
    p_name      => 'Semantic Search',
    p_page_mode => 'NORMAL'
  );
  apex_240200.wwv_flow_wizard_api.create_ir_region_on_col_info(
    p_flow_id      => 100,
    p_page_id      => 2,
    p_region_id    => l_region_id,
    p_region_title => 'Nearest Notes (Vector Search)',
    p_sql          =>
        'SELECT n.note_id, n.title, n.category, n.body, '
        || 'ROUND(VECTOR_DISTANCE(n.embedding, '
        || '  DBMS_VECTOR.UTL_TO_EMBEDDING(:P2_SEARCH, '
        || '    JSON(''{"provider":"database","model":"SYSTEM.ALL_MINILM"}'')'
        || '  ), COSINE), 4) AS similarity_distance '
        || 'FROM __APEX_USER__.notes n '
        || 'WHERE :P2_SEARCH IS NOT NULL '
        || 'ORDER BY similarity_distance '
        || 'FETCH FIRST 5 ROWS ONLY'
  );

  -- Get worksheet ID for page 2
  SELECT id INTO l_ws_id_p2
  FROM   apex_240200.wwv_flow_worksheets
  WHERE  flow_id = 100 AND page_id = 2;

  -- Worksheet columns for vector search results
  apex_240200.wwv_flow_imp.create_worksheet_column(
    p_id=>ROUND(DBMS_RANDOM.VALUE(1e9,9e9)), p_flow_id=>100, p_page_id=>2,
    p_worksheet_id=>l_ws_id_p2, p_db_column_name=>'NOTE_ID',
    p_display_order=>1, p_column_identifier=>'A',
    p_column_label=>'Note Id', p_report_label=>'Note Id',
    p_display_in_default_rpt=>'Y', p_is_sortable=>'Y',
    p_allow_sorting=>'Y', p_allow_filtering=>'Y', p_allow_highlighting=>'Y',
    p_allow_ctrl_breaks=>'Y', p_allow_aggregations=>'Y', p_allow_computations=>'Y',
    p_allow_charting=>'Y', p_allow_group_by=>'Y', p_allow_pivot=>'Y', p_allow_hide=>'Y',
    p_column_type=>'NUMBER', p_display_as=>'TEXT',
    p_heading_alignment=>'RIGHT', p_column_alignment=>'RIGHT'
  );
  apex_240200.wwv_flow_imp.create_worksheet_column(
    p_id=>ROUND(DBMS_RANDOM.VALUE(1e9,9e9)), p_flow_id=>100, p_page_id=>2,
    p_worksheet_id=>l_ws_id_p2, p_db_column_name=>'TITLE',
    p_display_order=>2, p_column_identifier=>'B',
    p_column_label=>'Title', p_report_label=>'Title',
    p_display_in_default_rpt=>'Y', p_is_sortable=>'Y',
    p_allow_sorting=>'Y', p_allow_filtering=>'Y', p_allow_highlighting=>'Y',
    p_allow_ctrl_breaks=>'Y', p_allow_aggregations=>'Y', p_allow_computations=>'Y',
    p_allow_charting=>'Y', p_allow_group_by=>'Y', p_allow_pivot=>'Y', p_allow_hide=>'Y',
    p_column_type=>'STRING', p_display_as=>'TEXT',
    p_heading_alignment=>'LEFT', p_column_alignment=>'LEFT'
  );
  apex_240200.wwv_flow_imp.create_worksheet_column(
    p_id=>ROUND(DBMS_RANDOM.VALUE(1e9,9e9)), p_flow_id=>100, p_page_id=>2,
    p_worksheet_id=>l_ws_id_p2, p_db_column_name=>'CATEGORY',
    p_display_order=>3, p_column_identifier=>'C',
    p_column_label=>'Category', p_report_label=>'Category',
    p_display_in_default_rpt=>'Y', p_is_sortable=>'Y',
    p_allow_sorting=>'Y', p_allow_filtering=>'Y', p_allow_highlighting=>'Y',
    p_allow_ctrl_breaks=>'Y', p_allow_aggregations=>'Y', p_allow_computations=>'Y',
    p_allow_charting=>'Y', p_allow_group_by=>'Y', p_allow_pivot=>'Y', p_allow_hide=>'Y',
    p_column_type=>'STRING', p_display_as=>'TEXT',
    p_heading_alignment=>'LEFT', p_column_alignment=>'LEFT'
  );
  apex_240200.wwv_flow_imp.create_worksheet_column(
    p_id=>ROUND(DBMS_RANDOM.VALUE(1e9,9e9)), p_flow_id=>100, p_page_id=>2,
    p_worksheet_id=>l_ws_id_p2, p_db_column_name=>'BODY',
    p_display_order=>4, p_column_identifier=>'D',
    p_column_label=>'Body', p_report_label=>'Body',
    p_display_in_default_rpt=>'Y', p_is_sortable=>'Y',
    p_allow_sorting=>'Y', p_allow_filtering=>'Y', p_allow_highlighting=>'Y',
    p_allow_ctrl_breaks=>'Y', p_allow_aggregations=>'Y', p_allow_computations=>'Y',
    p_allow_charting=>'Y', p_allow_group_by=>'Y', p_allow_pivot=>'Y', p_allow_hide=>'Y',
    p_column_type=>'STRING', p_display_as=>'TEXT',
    p_heading_alignment=>'LEFT', p_column_alignment=>'LEFT'
  );
  apex_240200.wwv_flow_imp.create_worksheet_column(
    p_id=>ROUND(DBMS_RANDOM.VALUE(1e9,9e9)), p_flow_id=>100, p_page_id=>2,
    p_worksheet_id=>l_ws_id_p2, p_db_column_name=>'SIMILARITY_DISTANCE',
    p_display_order=>5, p_column_identifier=>'E',
    p_column_label=>'Similarity', p_report_label=>'Similarity',
    p_display_in_default_rpt=>'Y', p_is_sortable=>'Y',
    p_allow_sorting=>'Y', p_allow_filtering=>'Y', p_allow_highlighting=>'Y',
    p_allow_ctrl_breaks=>'Y', p_allow_aggregations=>'Y', p_allow_computations=>'Y',
    p_allow_charting=>'Y', p_allow_group_by=>'Y', p_allow_pivot=>'Y', p_allow_hide=>'Y',
    p_column_type=>'NUMBER', p_display_as=>'TEXT',
    p_heading_alignment=>'RIGHT', p_column_alignment=>'RIGHT'
  );

  DBMS_OUTPUT.PUT_LINE('[4d] Page 2 (Vector Search IR + 5 columns) OK');

  -- Look up label and button template IDs from global UT42 entry.
  -- App's own wwv_flow_themes row doesn't exist yet (SYSDBA creates it in Step 4).
  SELECT default_label_template, default_button_template
  INTO   l_label_tpl, l_button_tpl
  FROM   apex_240200.wwv_flow_themes
  WHERE  theme_id = 42
  AND    theme_security_group_id IS NULL
  FETCH FIRST 1 ROW ONLY;

  -- Text field: P2_SEARCH (p_prompt = label; p_field_template is VARCHAR2)
  apex_240200.wwv_flow_imp.create_page_item(
    p_id                    => ROUND(DBMS_RANDOM.VALUE(1e9,9e9)),
    p_flow_id               => 100,
    p_flow_step_id          => 2,
    p_name                  => 'P2_SEARCH',
    p_data_type             => 'VARCHAR2',
    p_is_required           => false,
    p_item_sequence         => 10,
    p_item_plug_id          => l_region_id,
    p_display_as            => 'NATIVE_TEXT_FIELD',
    p_prompt                => 'Search',
    p_field_template        => TO_CHAR(l_label_tpl),
    p_item_template_options => '#DEFAULT#',
    p_attribute_01          => 'N',
    p_attribute_02          => 'N',
    p_attribute_04          => 'text'
  );

  -- Submit button: Go (p_id is first param, not p_button_id)
  apex_240200.wwv_flow_imp.create_page_button(
    p_id                      => ROUND(DBMS_RANDOM.VALUE(1e9,9e9)),
    p_flow_id                 => 100,
    p_flow_step_id            => 2,
    p_button_sequence         => 20,
    p_button_plug_id          => l_region_id,
    p_button_name             => 'GO',
    p_button_action           => 'SUBMIT',
    p_button_template_options => '#DEFAULT#',
    p_button_template_id      => l_button_tpl,
    p_button_image_alt        => 'Go',
    p_button_position         => 'BELOW_BOX'
  );

  DBMS_OUTPUT.PUT_LINE('[4e] P2_SEARCH item and Go button created');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('[4d/4e] Page 2 FAILED: ' || SQLERRM);
  RAISE;
END;
/

-- ── 4f. Navigation Menu + Navigation Bar lists ───────────────────────────────
--  Navigation Menu drives the hamburger/side nav (wired to app via
--  wwv_flows.navigation_list_id in Step 4 of load-sample-app.sh).
--  Navigation Bar drives the top-right nav bar (Sign Out, username).
DECLARE
  l_nav_menu_id  NUMBER := ROUND(DBMS_RANDOM.VALUE(1e9,9e9));
  l_nav_bar_id   NUMBER := ROUND(DBMS_RANDOM.VALUE(1e9,9e9));
BEGIN
  -- Navigation Menu list
  apex_240200.wwv_flow_imp.create_list(
    p_id           => l_nav_menu_id,
    p_flow_id      => 100,
    p_name         => 'Navigation Menu',
    p_list_type    => 'STATIC',
    p_list_status  => 'PUBLIC',
    p_list_displayed => 'BY_DEFAULT'
  );
  apex_240200.wwv_flow_imp.create_list_item(
    p_id                         => ROUND(DBMS_RANDOM.VALUE(1e9,9e9)),
    p_list_id                    => l_nav_menu_id,
    p_list_item_type             => 'LINK',
    p_list_item_status           => 'PUBLIC',
    p_item_displayed             => 'BY_DEFAULT',
    p_list_item_display_sequence => 10,
    p_list_item_link_text        => 'Notes',
    p_list_item_link_target      => 'f?p=&APP_ID.:1:&SESSION.::&DEBUG.::::'
  );
  apex_240200.wwv_flow_imp.create_list_item(
    p_id                         => ROUND(DBMS_RANDOM.VALUE(1e9,9e9)),
    p_list_id                    => l_nav_menu_id,
    p_list_item_type             => 'LINK',
    p_list_item_status           => 'PUBLIC',
    p_item_displayed             => 'BY_DEFAULT',
    p_list_item_display_sequence => 20,
    p_list_item_link_text        => 'Semantic Search',
    p_list_item_link_target      => 'f?p=&APP_ID.:2:&SESSION.::&DEBUG.::::'
  );

  -- Navigation Bar list (top-right: username display + Sign Out)
  apex_240200.wwv_flow_imp.create_list(
    p_id           => l_nav_bar_id,
    p_flow_id      => 100,
    p_name         => 'Navigation Bar',
    p_list_type    => 'STATIC',
    p_list_status  => 'PUBLIC',
    p_list_displayed => 'BY_DEFAULT'
  );
  apex_240200.wwv_flow_imp.create_list_item(
    p_id                         => ROUND(DBMS_RANDOM.VALUE(1e9,9e9)),
    p_list_id                    => l_nav_bar_id,
    p_list_item_type             => 'LINK',
    p_list_item_status           => 'PUBLIC',
    p_item_displayed             => 'BY_DEFAULT',
    p_list_item_display_sequence => 10,
    p_list_item_link_text        => '&APP_USER.',
    p_list_item_link_target      => '#'
  );
  apex_240200.wwv_flow_imp.create_list_item(
    p_id                         => ROUND(DBMS_RANDOM.VALUE(1e9,9e9)),
    p_list_id                    => l_nav_bar_id,
    p_list_item_type             => 'LINK',
    p_list_item_status           => 'PUBLIC',
    p_item_displayed             => 'BY_DEFAULT',
    p_list_item_display_sequence => 20,
    p_list_item_link_text        => 'Sign Out',
    p_list_item_link_target      => '&LOGOUT_URL.'
  );

  DBMS_OUTPUT.PUT_LINE('[4f] Navigation Menu and Navigation Bar created');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('[4f] Navigation lists FAILED: ' || SQLERRM);
  RAISE;
END;
/

-- ── 5. End import context + commit ────────────────────────────────────────────
BEGIN
  apex_240200.wwv_flow_imp.component_end;
  DBMS_OUTPUT.PUT_LINE('[5] component_end OK');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('[5] component_end skipped: ' || SQLERRM);
END;
/

COMMIT;

-- ── Verify ────────────────────────────────────────────────────────────────────
SET FEEDBACK OFF
PROMPT
PROMPT === App 100 state ===
SELECT check_item, result FROM (
  SELECT 'application'         AS check_item,
         CASE WHEN COUNT(*) > 0 THEN 'YES' ELSE 'NO - FAILED' END AS result
  FROM   apex_applications WHERE application_id = 100
  UNION ALL
  SELECT 'login page (9999)',
         CASE WHEN COUNT(*) > 0 THEN 'YES' ELSE 'NO' END
  FROM   apex_application_pages WHERE application_id = 100 AND page_id = 9999
  UNION ALL
  SELECT 'page 1 (Notes)',
         CASE WHEN COUNT(*) > 0 THEN 'YES' ELSE 'NO' END
  FROM   apex_application_pages WHERE application_id = 100 AND page_id = 1
  UNION ALL
  SELECT 'page 2 (Search)',
         CASE WHEN COUNT(*) > 0 THEN 'YES' ELSE 'NO' END
  FROM   apex_application_pages WHERE application_id = 100 AND page_id = 2
);

PROMPT
PROMPT === URLs ===
PROMPT   Login:        http://localhost:__APEX_PORT__/ords/f?p=100:9999
PROMPT   Notes IR:     http://localhost:__APEX_PORT__/ords/f?p=100:1
PROMPT   Vector Search:http://localhost:__APEX_PORT__/ords/f?p=100:2
PROMPT   Workspace=__APEX_USER__  User=__APEX_USER__  Password=__APEX_PASSWORD__

exit
