#!/usr/bin/env bash
# run-dbfree.sh — main orchestrator for the dbfree/ POC stack.
#
# Usage:
#   ./run-dbfree.sh          Bring the stack up (compose up, install APEX/ORDS, wait ready)
#   ./run-dbfree.sh -c        Clean: docker compose down + wipe DB/ORDS state
#                          (APEX_INSTALL_DIR/ORDS_INSTALL_DIR are left alone — not stateful)
#   ./run-dbfree.sh -c -r     Clean, and also remove the pulled Docker images
#   ./run-dbfree.sh -h        Show this help
#
# Non-interactive by design (no prompts) so it can be driven by
# test/full-cycle-test.sh unattended.

set -euo pipefail
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/lib.sh"

CLEAN=0
REMOVE_IMAGES=0
while getopts ":crh" opt; do
    case $opt in
        c) CLEAN=1 ;;
        r) REMOVE_IMAGES=1 ;;
        h) grep '^#' "$0" | sed 's/^# \{0,1\}//; /^!/d'; exit 0 ;;
        \?) echo "ERROR: Unknown option -$OPTARG"; exit 1 ;;
    esac
done

cd "$DBFREE_DIR"

# Generates the script that runs inside the plain-JRE "ords" container as its
# entrypoint (docker-compose.yml bind-mounts it in read-only). Not part of any
# official Oracle image: the official ords container needs an OTN registry
# login, so this toolkit runs ORDS standalone from the zip distribution
# instead (see download_ords() in setup-for-dbfree.sh).
#
# First boot: installs the ORDS schema/connection pool non-interactively
# (--password-stdin). Subsequent boots: skip straight to serving, guarded by
# a marker file the script creates itself (not an ORDS-internal file, so it
# doesn't depend on guessing ORDS's config layout).
write_ords_entrypoint() {
    cat > "$SCRIPT_DIR/ords-entrypoint.sh" <<'EOF'
#!/usr/bin/env bash
# Generated by run-dbfree.sh (write_ords_entrypoint) — do not edit by hand.
#
# Required env vars (set by docker-compose.yml):
#   SYS_PASSWORD, ORDS_PUBLIC_USER_PASSWORD, DB_HOST, DB_PORT, DB_SERVICENAME

set -euo pipefail

CONFIG_DIR="/etc/ords/config"
MARKER="$CONFIG_DIR/.installed"
LOG_DIR="$CONFIG_DIR/logs"
mkdir -p "$LOG_DIR"

if [ ! -f "$MARKER" ]; then
    echo "=== ORDS install (first boot) ==="
    printf '%s\n%s\n' "$SYS_PASSWORD" "$ORDS_PUBLIC_USER_PASSWORD" | \
        ./bin/ords --config "$CONFIG_DIR" install \
            --admin-user SYS \
            --db-hostname "$DB_HOST" \
            --db-port "$DB_PORT" \
            --db-servicename "$DB_SERVICENAME" \
            --proxy-user \
            --log-folder "$LOG_DIR" \
            --password-stdin
    touch "$MARKER"
    echo "=== ORDS install complete ==="
else
    echo "ORDS already installed (marker found at $MARKER) — skipping install."
fi

echo "=== Starting ORDS standalone ==="
# Note: unlike `install`, the `serve` command does not accept --log-folder.
exec ./bin/ords --config "$CONFIG_DIR" serve \
    --apex-images /opt/oracle/apex/images \
    --port 8080
EOF
    chmod +x "$SCRIPT_DIR/ords-entrypoint.sh"
}

if [ "$CLEAN" -eq 1 ]; then
    hdr "Cleaning dbfree/ stack"
    docker compose down --remove-orphans || true

    DB_DATA_DIR="$(resolve_dbfree_path DB_DATA_DIR ./oradata)"
    ORDS_CONFIG_DIR="$(resolve_dbfree_path ORDS_CONFIG_DIR ./ords_config)"

    for d in "$DB_DATA_DIR" "$ORDS_CONFIG_DIR"; do
        if [ -d "$d" ]; then
            # The DB container creates its own files/dirs as uid 54321
            # (oracle) with restrictive permissions — a plain host-user `rm
            # -rf` can hit "Permission denied" on the directories it made
            # even though the top-level dir itself is chmod 777. Delete via
            # a throwaway root container instead, so cleanup is reliable
            # regardless of what perms the DB left behind.
            docker run --rm -v "$d:/target" alpine sh -c 'rm -rf /target/* /target/.[!.]* 2>/dev/null; true'
            ok "Wiped $d"
        fi
    done

    if [ "$REMOVE_IMAGES" -eq 1 ]; then
        DOCKER_IMAGE="$(select_docker_image)"
        ORDS_JAVA_IMAGE="$(ini_val ORDS_JAVA_IMAGE)"
        [ -n "$DOCKER_IMAGE" ] && docker rmi "$DOCKER_IMAGE" 2>/dev/null || true
        [ -n "$ORDS_JAVA_IMAGE" ] && docker rmi "$ORDS_JAVA_IMAGE" 2>/dev/null || true
        ok "Removed pulled images"
    fi

    ok "Clean complete."
    exit 0
fi

# ── Bring the stack up ────────────────────────────────────────────────────
# Arch-aware, exported so docker-compose.yml's ${DOCKER_IMAGE:-...} picks
# this up instead of its own (arm64-only) fallback default.
export DOCKER_IMAGE="$(select_docker_image)"
ORACLE_PWD="$(ini_val ORACLE_PWD)"
ORACLE_PDB="$(ini_val ORACLE_PDB)"; ORACLE_PDB="${ORACLE_PDB:-FREEPDB1}"
CONTAINER_NAME="$(ini_val CONTAINER_NAME)"; CONTAINER_NAME="${CONTAINER_NAME:-caseweave-dbfree-db}"
ORDS_CONTAINER_NAME="$(ini_val ORDS_CONTAINER_NAME)"; ORDS_CONTAINER_NAME="${ORDS_CONTAINER_NAME:-caseweave-dbfree-ords}"
APEX_PORT="$(ini_val APEX_PORT)"; APEX_PORT="${APEX_PORT:-8092}"
DB_HOST_PORT="$(ini_val DB_HOST_PORT)"; DB_HOST_PORT="${DB_HOST_PORT:-15216}"
DB_HEALTHY_TIMEOUT="$(ini_val DB_HEALTHY_TIMEOUT)"; DB_HEALTHY_TIMEOUT="${DB_HEALTHY_TIMEOUT:-900}"
ORDS_HEALTHY_TIMEOUT="$(ini_val ORDS_HEALTHY_TIMEOUT)"; ORDS_HEALTHY_TIMEOUT="${ORDS_HEALTHY_TIMEOUT:-600}"
DEFAULT_PASSWORD="$(ini_val DEFAULT_PASSWORD)"
OLLAMA_BASE_URL="$(ini_val OLLAMA_BASE_URL)"; OLLAMA_BASE_URL="${OLLAMA_BASE_URL:-http://host.docker.internal:11434}"
OLLAMA_MODEL="$(ini_val OLLAMA_MODEL)"; OLLAMA_MODEL="${OLLAMA_MODEL:-llama3.2:3b}"
EZCONNECT="//localhost:$DB_HOST_PORT/$ORACLE_PDB"

[ -n "$ORACLE_PWD" ] || die "ORACLE_PWD not set — add ORACLE_PWD=<password> to dbfree/.env (see .env.sample)."
[ -n "$DEFAULT_PASSWORD" ] || die "DEFAULT_PASSWORD not set — add DEFAULT_PASSWORD=<password> to dbfree/.env (see .env.sample). This is the one password used for the compat ADMIN user and load-apex-app.sh."

# Fail fast if the extracted APEX/ORDS distributions aren't there yet.
APEX_INSTALL_DIR="$(resolve_dbfree_path APEX_INSTALL_DIR ./apex-install)"
ORDS_INSTALL_DIR="$(resolve_dbfree_path ORDS_INSTALL_DIR ./ords-install)"
[ -f "$APEX_INSTALL_DIR/apexins.sql" ] || die "APEX not found under $APEX_INSTALL_DIR — run ./setup-for-dbfree.sh first."
[ -x "$ORDS_INSTALL_DIR/bin/ords" ] || die "ORDS not found under $ORDS_INSTALL_DIR — run ./setup-for-dbfree.sh first."

hdr "Starting oracle-db"
docker compose up -d oracle-db

echo "Waiting up to ${DB_HEALTHY_TIMEOUT}s for $CONTAINER_NAME to be healthy..."
start=$(date +%s)
while true; do
    elapsed=$(( $(date +%s) - start ))
    [ "$elapsed" -ge "$DB_HEALTHY_TIMEOUT" ] && die "Timeout waiting for $CONTAINER_NAME to become healthy."
    status=$(docker inspect --format='{{.State.Health.Status}}' "$CONTAINER_NAME" 2>/dev/null || echo "starting")
    [ "$status" = "healthy" ] && { ok "$CONTAINER_NAME is healthy (${elapsed}s)"; break; }
    [ "$status" = "unhealthy" ] && die "$CONTAINER_NAME reported unhealthy — check: docker logs $CONTAINER_NAME. Common causes: Colima/Docker Desktop has too little memory allocated (the DB wants a few GB headroom beyond its own SGA/PGA), the host is out of disk space, or (on macOS/Colima) a stuck NAT state on DB_HOST_PORT — see README.md's stuck-port gotcha."
    sleep 10
done

enable_extended_string_size "$CONTAINER_NAME" "$ORACLE_PDB" "$DB_HEALTHY_TIMEOUT"

DB_PGA_AGGREGATE_LIMIT="$(ini_val DB_PGA_AGGREGATE_LIMIT)"; DB_PGA_AGGREGATE_LIMIT="${DB_PGA_AGGREGATE_LIMIT:-3G}"
set_pga_aggregate_limit "$CONTAINER_NAME" "$DB_PGA_AGGREGATE_LIMIT"

# Password-based EZConnect straight at the PDB service (not OS-authenticated
# bequeath "/") — this lands directly inside the PDB with no CDB$ROOT/ALTER
# SESSION dance needed, for any step that's pure SQL. sqlplus_setup_env
# (lib.sh) sets up DBFREE_SQLPLUS + a clean TNS_ADMIN/LD_LIBRARY_PATH so we can
# invoke sqlplus directly with positional script args.
sqlplus_setup_env

# Run twice: once now (creates the compat ADMIN user early, needed by
# steps below) and again after APEX installs (grants
# APEX_ADMINISTRATOR_ROLE, which doesn't exist until APEX does — see
# create-admin-compat-user.sql.tpl). Idempotent either way.
bootstrap_compat_admin_user() {
    hdr "Bootstrapping compat ADMIN user"
    # mktemp with a literal suffix after XXXXXX (e.g. "...XXXXXX.sql") is not
    # portable: macOS/BSD mktemp doesn't randomize in that form and returns
    # the same fixed name every call, colliding once the file exists
    # (confirmed empirically) — mktemp with no template, then rename, works
    # on both.
    local admin_sql
    admin_sql="$(mktemp)"; mv "$admin_sql" "$admin_sql.sql"; admin_sql="$admin_sql.sql"
    sed -e "s/__ADMIN_PASSWORD__/$DEFAULT_PASSWORD/g" \
        "$SCRIPT_DIR/sql-scripts/create-admin-compat-user.sql.tpl" > "$admin_sql"
    local admin_out
    admin_out="$("$DBFREE_SQLPLUS" -s "sys/$ORACLE_PWD@$EZCONNECT as sysdba" "@$admin_sql" 2>&1 < /dev/null)"
    rm -f "$admin_sql"
    echo "$admin_out"
    echo "$admin_out" | grep -qiE "SP2-|ORA-|PLS-" && die "Failed to bootstrap the compat ADMIN user — see sqlplus output above. If this is ORA-01017/ORA-01005 (invalid credential), DEFAULT_PASSWORD in dbfree/.env was probably changed after this ADMIN user was first created — either change it back, or wipe oradata/ with ./run-dbfree.sh -c and redeploy with the new password."
    ok "Compat ADMIN user ready"
}
bootstrap_compat_admin_user

hdr "Checking for an existing APEX install"
CHECK_SQL="$(mktemp)"; mv "$CHECK_SQL" "$CHECK_SQL.sql"; CHECK_SQL="$CHECK_SQL.sql"
cat > "$CHECK_SQL" <<'SQL'
SET PAGESIZE 0 FEEDBACK OFF HEADING OFF VERIFY OFF
SELECT COUNT(*) FROM dba_users WHERE username LIKE 'APEX\_2%' ESCAPE '\' AND oracle_maintained = 'Y';
exit;
SQL
APEX_COUNT="$("$DBFREE_SQLPLUS" -s "sys/$ORACLE_PWD@$EZCONNECT as sysdba" "@$CHECK_SQL" < /dev/null | tr -d '[:space:]')"
rm -f "$CHECK_SQL"

if [ "$APEX_COUNT" != "0" ]; then
    ok "APEX already installed in this PDB — skipping apexins.sql/apex_rest_config.sql (found $APEX_COUNT schema(s))."
else
    hdr "Installing APEX (apexins.sql — this takes a while, expect 15-30 minutes)"
    # apexins.sql's nested @@core/scripts/*.sql references only resolve
    # correctly when sqlplus's actual working directory is apexins.sql's own
    # directory AND it's invoked via a bare relative filename — a full-path
    # "@script args" invocation from a different cwd was tried and does NOT
    # work here despite matching Oracle's documented @@ semantics (confirmed
    # empirically). apexins.sql is pure SQL (no shell-outs), so it doesn't
    # need to run inside the container — just cd into its directory on the host.
    #
    # `< /dev/null`: apexins.sql is Oracle's own file, invoked via a bare
    # command-line "@script" arg (not a heredoc) — unlike every other
    # sqlplus call in this toolkit, we don't control its content and can't
    # guarantee it ends with its own EXIT. Without a script-level EXIT,
    # sqlplus drops into interactive mode once it finishes and waits on
    # whatever stdin this command substitution inherited — which can hang
    # indefinitely if that happens to be a real terminal. Redirecting from
    # /dev/null forces immediate EOF the moment sqlplus tries to read more
    # input, so it exits cleanly regardless of whether the script itself
    # has an EXIT.
    APEXINS_OUT="$(cd "$APEX_INSTALL_DIR" && "$DBFREE_SQLPLUS" -s "sys/$ORACLE_PWD@$EZCONNECT as sysdba" "@apexins.sql" SYSAUX SYSAUX TEMP /i/ 2>&1 < /dev/null)"
    echo "$APEXINS_OUT"
    echo "$APEXINS_OUT" | grep -qiE "SP2-|ORA-|PLS-" && die "apexins.sql failed — see sqlplus output above. This step is pure SQL and runs for 15-30 minutes; a failure partway through usually means disk space ran out (check df -h) or the container was killed/restarted mid-install (check docker logs $CONTAINER_NAME). A partial install can leave APEX in a broken state — if in doubt, ./run-dbfree.sh -c and redeploy from scratch."
    ok "APEX installed"

    hdr "Creating the APEX instance administrator"
    # A database user named ADMIN (create-admin-compat-user.sql.tpl, above)
    # is NOT the same thing as APEX's own INTERNAL-workspace instance
    # administrator — that's a separate record in wwv_flow_fnd_user, normally
    # created by apxchpwd.sql. Without one, apex_instance_admin.add_workspace
    # (used by load-apex-app.sh (this directory) for every app import) fails with
    # ORA-20987 ("User ADMIN requires ADMIN privilege") even though the DB
    # user ADMIN already has DBA.
    #
    # apxchpwd.sql itself is NOT used here: its `ACCEPT ... HIDE` prompt for
    # the password does not correctly read piped (non-TTY) stdin on this
    # SQL*Plus version — it silently returns an empty string instead of the
    # piped value, which both raises ORA-20001 (blank password rejected) AND
    # leaves the real password line unconsumed, so it gets misinterpreted as
    # a stray top-level SQL*Plus command afterwards (SP2-0734). Confirmed
    # empirically: the identical password succeeds when passed as a literal
    # PL/SQL argument (below) instead of through the ACCEPT/HIDE prompt.
    # This calls the exact same underlying procedure apxchpwd.sql itself
    # calls, just without the broken prompt in between.
    APXADMIN_OUT="$(cd "$APEX_INSTALL_DIR" && "$DBFREE_SQLPLUS" -s "sys/$ORACLE_PWD@$EZCONNECT as sysdba" <<SQLEOF 2>&1
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
@@core/scripts/set_appun.sql
ALTER SESSION SET CURRENT_SCHEMA = &APPUN;
BEGIN
  wwv_flow_instance_admin.create_or_update_admin_user(
    p_username => 'ADMIN',
    p_email    => 'admin@example.com',
    p_password => '$DEFAULT_PASSWORD'
  );
  COMMIT;
END;
/
exit
SQLEOF
)"
    echo "$APXADMIN_OUT"
    echo "$APXADMIN_OUT" | grep -qiE "SP2-|ORA-|PLS-" && die "Creating the APEX instance administrator failed — see sqlplus output above. If this is ORA-20001 (blank password rejected), something fed an empty DEFAULT_PASSWORD through — double check it's actually set in dbfree/.env, not just present as an empty key."
    ok "APEX instance administrator ready"

    hdr "Configuring APEX_LISTENER / APEX_REST_PUBLIC_USER (apex_rest_config.sql)"
    # This one DOES need to run inside the container via docker exec: on a
    # CDB, apex_rest_config.sql shells out to $ORACLE_HOME/perl/.../catcon.pl
    # (a real Oracle Home, which only exists in the container, not on the
    # host's thin Instant Client) to iterate PDBs. Same cwd requirement as
    # apexins.sql applies — `docker exec -w` sets it to the container-internal
    # /tmp/apex mount, with a bare relative filename. It prompts (via ACCEPT,
    # or catcon.pl-forwarded prompts) for the APEX_LISTENER then
    # APEX_REST_PUBLIC_USER passwords, in that order — fed via stdin. Reusing
    # ORACLE_PWD for both is a deliberate POC shortcut.
    RESTCFG_OUT="$(printf '%s\n%s\n' "$ORACLE_PWD" "$ORACLE_PWD" \
        | docker exec -i -w /tmp/apex "$CONTAINER_NAME" sqlplus -s "sys/$ORACLE_PWD@localhost:1521/$ORACLE_PDB as sysdba" "@apex_rest_config.sql" 2>&1)"
    echo "$RESTCFG_OUT"
    echo "$RESTCFG_OUT" | grep -qiE "SP2-|ORA-|PLS-" && die "apex_rest_config.sql failed — see sqlplus output above. This one runs inside the container via docker exec and shells out to catcon.pl — if the error is about a missing file/cwd, check the container is actually healthy (docker ps); if it's a password prompt issue, this reuses ORACLE_PWD for both APEX_LISTENER and APEX_REST_PUBLIC_USER, so a non-ASCII or oddly-quoted ORACLE_PWD in dbfree/.env is worth checking."
    ok "APEX REST config complete"
fi

# Re-run now that APEX_ADMINISTRATOR_ROLE exists (see the function's
# definition above and create-admin-compat-user.sql.tpl) — harmless/idempotent
# if it was already granted on a previous run.
bootstrap_compat_admin_user

hdr "Starting ords (standalone install + serve)"
write_ords_entrypoint
docker compose up -d ords

echo "Waiting up to ${ORDS_HEALTHY_TIMEOUT}s for ORDS to answer on port $APEX_PORT..."
start=$(date +%s)
while true; do
    elapsed=$(( $(date +%s) - start ))
    [ "$elapsed" -ge "$ORDS_HEALTHY_TIMEOUT" ] && die "Timeout waiting for ORDS on port $APEX_PORT. Check: docker logs $ORDS_CONTAINER_NAME"
    if curl -sf -o /dev/null "http://localhost:$APEX_PORT/ords/"; then
        ok "ORDS responding on port $APEX_PORT (${elapsed}s)"
        break
    fi
    sleep 10
done

ensure_host_firewall_allows_ollama

hdr "Granting UTL_HTTP/DBMS_VECTOR_CHAIN to ADMIN (as SYS)"
# Must run as SYS, not ADMIN: `GRANT ... TO ADMIN` while connected AS ADMIN
# is a self-grant, which Oracle rejects unconditionally with ORA-01749
# regardless of whether the grant already took effect previously —
# confirmed empirically. setup-dbfree-network-ai.sql.tpl (run as ADMIN, below)
# used to attempt this itself and always failed.
GRANTS_SQL="$(mktemp)"; mv "$GRANTS_SQL" "$GRANTS_SQL.sql"; GRANTS_SQL="$GRANTS_SQL.sql"
cat > "$GRANTS_SQL" <<'SQL'
GRANT EXECUTE ON SYS.UTL_HTTP TO ADMIN;
GRANT EXECUTE ON CTXSYS.DBMS_VECTOR_CHAIN TO ADMIN;
exit;
SQL
GRANTS_OUT="$("$DBFREE_SQLPLUS" -s "sys/$ORACLE_PWD@$EZCONNECT as sysdba" "@$GRANTS_SQL" 2>&1 < /dev/null)"
rm -f "$GRANTS_SQL"
echo "$GRANTS_OUT"
echo "$GRANTS_OUT" | grep -qiE "SP2-|ORA-|PLS-" && die "Failed to grant UTL_HTTP/DBMS_VECTOR_CHAIN to ADMIN — see sqlplus output above."
ok "UTL_HTTP/DBMS_VECTOR_CHAIN granted to ADMIN"

hdr "Network/AI setup"
NET_SQL="$(mktemp)"; mv "$NET_SQL" "$NET_SQL.sql"; NET_SQL="$NET_SQL.sql"
sed -e "s|__OLLAMA_BASE_URL__|$OLLAMA_BASE_URL|g" \
    -e "s/__OLLAMA_MODEL__/$OLLAMA_MODEL/g" \
    "$SCRIPT_DIR/sql-scripts/setup-dbfree-network-ai.sql.tpl" > "$NET_SQL"
run_sql_ezconnect "ADMIN" "$DEFAULT_PASSWORD" "$EZCONNECT" "$NET_SQL" \
    || warn "Network/AI setup script reported an error — review sqlplus output above (Ollama connectivity failure is non-fatal for this step). If it's ORA-29273 (HTTP request failed) on Linux, see the firewall check earlier in this run — a hardened host's iptables INPUT chain is the usual cause, not Ollama itself."
rm -f "$NET_SQL"

echo ""
ok "Stack is up."
echo "  APEX      : http://localhost:$APEX_PORT/ords/apex"
echo "  ORDS      : http://localhost:$APEX_PORT/ords/"
echo "  SQL*Net   : $EZCONNECT (ADMIN / <DEFAULT_PASSWORD from dbfree/.env>)"
echo ""
echo "  Verify with: ./test/smoke-dbfree.sh"
