# Sample config.ini content
# Place this file in the same directory as the script

# # to use a remote hostname this needs to be a valid FQDN or in /etc/hosts so that certs are generated correctly 
# e.g. myhost.local must be in /etc/hosts on the remote and on the local machine
# also make sure port 8443 is open just 443 is not sufficient (at least on azure cloud)
# adjust this for your environment
HOSTNAME=fu9.local

# Oracle Instant Client
# only needs changing when the instant client gets updated 
BASIC_ZIP=instantclient-basic-linux.x64-23.6.0.24.10.zip
SQLPLUS_ZIP=instantclient-sqlplus-linux.x64-23.6.0.24.10.zip
BASIC_URL=https://download.oracle.com/otn_software/linux/instantclient/2360000/instantclient-basic-linux.x64-23.6.0.24.10.zip
SQLPLUS_URL=https://download.oracle.com/otn_software/linux/instantclient/2360000/instantclient-sqlplus-linux.x64-23.6.0.24.10.zip
INSTANT_CLIENT=instantclient_23_6

# only change this if you need a different model 
ONNX_MODEL_URL=https://adwc4pm.objectstorage.us-ashburn-1.oci.customer-oci.com/p/eLddQappgBJ7jNi6Guz9m9LOtYe2u8LWY19GfgU8flFK4N9YgP4kTlrE9Px3pE12/n/adwc4pm/b/OML-Resources/o/all_MiniLM_L12_v2.onnx


# should not need to change these 
#VOL_NAME=adb_container_vol
#DB_DATA_DIR=db_data_dir
CONTAINER_NAME=adb-free
DOCKER_IMAGE=container-registry.oracle.com/database/adb-free:latest-23ai
DEFAULT_PASSWORD=Welcome_MY_ATP_123